# Generated by Django 6.0 on 2025-12-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talents_project',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'talents_skill',
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'talents_talentprofile',
            },
        ),
        migrations.CreateModel(
            name='TalentProfileFeaturedProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'talents_talentprofile_featured_projects',
            },
        ),
        migrations.CreateModel(
            name='TalentProfileLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'talents_talentprofile_languages',
            },
        ),
        migrations.CreateModel(
            name='TalentProfileSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'talents_talentprofile_skills',
            },
        ),
        migrations.CreateModel(
            name='TalentValidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talents_talentvalidation',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'talents_language',
                'unique_together': {('name', 'level')},
            },
        ),
    ]
