# Generated by Django 6.0 on 2025-12-04 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentprofilefeaturedproject',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='talents.project'),
        ),
        migrations.AddField(
            model_name='talentprofilefeaturedproject',
            name='talentprofile',
            field=models.ForeignKey(db_column='talentprofile_id', on_delete=django.db.models.deletion.CASCADE, to='talents.talentprofile'),
        ),
        migrations.AddField(
            model_name='talentprofilelanguage',
            name='language',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='talents.language'),
        ),
        migrations.AddField(
            model_name='talentprofilelanguage',
            name='talentprofile',
            field=models.ForeignKey(db_column='talentprofile_id', on_delete=django.db.models.deletion.CASCADE, to='talents.talentprofile'),
        ),
        migrations.AddField(
            model_name='talentprofileskill',
            name='skill',
            field=models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='talents.skill'),
        ),
        migrations.AddField(
            model_name='talentprofileskill',
            name='talentprofile',
            field=models.ForeignKey(db_column='talentprofile_id', on_delete=django.db.models.deletion.CASCADE, to='talents.talentprofile'),
        ),
        migrations.AddField(
            model_name='talentvalidation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentvalidation',
            name='validated_by',
            field=models.ForeignKey(db_column='validated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='talentprofilefeaturedproject',
            unique_together={('talentprofile', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='talentprofilelanguage',
            unique_together={('talentprofile', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='talentprofileskill',
            unique_together={('talentprofile', 'skill')},
        ),
    ]
