# Generated by Django 6.0 on 2025-12-04 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0001_initial'),
        ('talents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationapplication',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationapplication',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='collaboration.collaborationrequest'),
        ),
        migrations.AddField(
            model_name='collaborationrequestskill',
            name='collaborationrequest',
            field=models.ForeignKey(db_column='collaborationrequest_id', on_delete=django.db.models.deletion.CASCADE, to='collaboration.collaborationrequest'),
        ),
        migrations.AddField(
            model_name='collaborationrequestskill',
            name='skill',
            field=models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='talents.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborationapplication',
            unique_together={('request', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='collaborationrequestskill',
            unique_together={('collaborationrequest', 'skill')},
        ),
    ]
